<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Continuous Operation Application</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        h2 { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        td { padding: 6px; vertical-align: top; }
        .section-title { background: #f0f0f0; padding: 8px; font-weight: bold; margin-top: 20px; }
   <style>
    .stamp-container {
        position: fixed;
        bottom: 120px;
        right: 80px;
        width: 180px;
        text-align: center;
        font-family: monospace;
    }

    .stamp-image {
        width: 10%;
    }

    .stamp-date {
        position: absolute;
        top: 85px; /* adjust to fit inside circle */
        left: 0;
        right: 0;
        font-size: 12px;
        font-weight: bold;
    }
</style>

</head>
<body>

    <h2>Continuous Operation Application</h2>

    <div class="section-title">Employer Details</div>
    <table>
        <tr>
            <td><strong>Employer Name:</strong></td>
            <td>{{ $application->employer_name }}</td>
        </tr>
        <tr>
            <td><strong>Registration Number:</strong></td>
            <td>{{ $application->registration_number }}</td>
        </tr>
        <tr>
            <td><strong>Contact Person:</strong></td>
            <td>{{ $application->contact_person }}</td>
        </tr>
        <tr>
            <td><strong>Postal Address:</strong></td>
            <td>{{ $application->postal_address }}</td>
        </tr>
        <tr>
            <td><strong>Telephone:</strong></td>
            <td>{{ $application->telephone }}</td>
        </tr>
        <tr>
            <td><strong>Email:</strong></td>
            <td>{{ $application->email }}</td>
        </tr>
    </table>

    <div class="section-title">Business Information</div>
    <table>
        <tr>
            <td><strong>Nature of Business:</strong></td>
            <td>{{ $application->nature_of_business }}</td>
        </tr>
        <tr>
            <td><strong>Motivation:</strong></td>
            <td>{{ $application->motivation }}</td>
        </tr>
        <tr>
            <td><strong>Period:</strong></td>
            <td>{{ $application->period }}</td>
        </tr>
    </table>

    <div class="section-title">Operational Details</div>
    <table>
        <tr>
            <td><strong>Employee Categories:</strong></td>
            <td>{{ $application->employee_categories }}</td>
        </tr>

        <tr>
            <td><strong>Number of Shifts:</strong></td>
            <td>{{ $application->number_of_shifts }}</td>
        </tr>

        <tr>
            <td><strong>Hours Per Shift:</strong></td>
            <td>{{ $application->hours_per_shift }}</td>
        </tr>

        <tr>
            <td><strong>Off Days:</strong></td>
            <td>{{ $application->off_days }}</td>
        </tr>

        <tr>
            <td><strong>Date Signed:</strong></td>
            <td>{{ $application->date_signed }}</td>
        </tr>
    </table>

    @if ($application->shift_roster)
        <p><strong>Shift Roster File:</strong> Attached (uploaded by user)</p>
    @endif

    @if ($application->approved_document)
        <p><strong>Approved Document:</strong> Attached (uploaded by admin)</p>
    @endif

    <p><strong>Status:</strong> {{ $application->status }}</p>
<div class="stamp-container">
    <img src="{{ public_path('images/stamp-preview.png') }}" class="stamp-image">



    <div class="stamp-date">
        {{ now('Africa/Windhoek')->format('Y-m-d') }}
    </div>
</div>

    <br><br>
    <p style="text-align:center;">Generated by MoJLR Exemption , Variation and Overtime Application System | {{ date('Y-m-d H:i') }}</p>


</body>
</html>
