<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Continuous Operation Application</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        h2 { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        td { padding: 6px; vertical-align: top; }
        td.label { width: 30%; font-weight: bold; }
        td.value { width: 70%; }
        .section-title { background: #f0f0f0; padding: 8px; font-weight: bold; margin-top: 20px; }
    </style>
</head>
<body>
<div style="text-align: center; font-size: 12px;">
  <h4>REPUBLIC OF NAMIBIA</h4>
  <h4>LABOUR ACT, 2007<br>(Section 139) (Regulation 26(1))</h4>
  <h4>APPLICATION FOR EXEMPTION OR VARIATION FROM CHAPTER 3</h4>
  </div>
  <h4>
    Instruction: Attach hereto a detailed statement supporting the proposed exemption(s) or variation(s) of one or more of the Basic Conditions of Employment, including:<br>
    1. Sections or subsections for which you seek exemption and the reasons therefor;<br>
    2. Sections or subsections that you propose to vary, if any, the proposed language for each variation, and the reasons therefor;<br>
    3. Specification of employees or categories of employees that would be affected by exemption or variation; and<br>
    4. Written submission on behalf of affected employees, or, if not possible, evidence of consultation with employees, reflecting their views of each of the proposed exemptions or variations.
  </h4>

    <div class="section-title">Applicant Details</div>
        <table>
            <tr>
            <td class="label">Name of applicant</td>
            <td class="value">{{ $application->applicant_name }}</td>
        </tr>
        <tr>
            <td class="label">Address</td>
            <td class="value">{{ $application->address}}</td>
        </tr>
        <tr>
            <td class="label">Sections of the Labour Act, 2007, from which exemption or variation is sought.</td>
            <td class="value">  @if($application->sections->isNotEmpty())
            {{ $application->sections->pluck('name')->join(', ') }}
        @else
            N/A
        @endif</td>
        </tr>
        <tr>
            <td class="label">Category or categories of employees that would be affected by exemption or variation</td>
            <td class="value">{{ $application->categories_affected}}</td>
        </tr>
        <tr>
            <td class="label">Representative of Applicant (print name and sign)	</td>
            <td class="value">{{ $application->representative_name}}</td>
        </tr>
        <tr>
            <td class="label">Position</td>
            <td class="value">{{ $application->position}}</td>
        </tr>
        <tr>
            <td class="label">Date: </td>
            <td class="value">{{ $application->application_date}}</td>
        </tr>
        <tr>
</table>

     <p style="text-align:center;">Generated by MoJLR Exemption , Variation and Overtime Application System | {{ date('Y-m-d H:i') }}</p>


</body>
</html>
