<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Overtime Application</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        h2 { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        td { padding: 6px; vertical-align: top; }
        .section-title { background: #f0f0f0; padding: 8px; font-weight: bold; margin-top: 20px; }
    </style>
</head>
<body>

    <h2>APPLICATION TO EXCEED OVERTIME LIMIT IN TERMS OF SECTION 17(4) AND OBTAIN APPROVAL TO PERFORM WORK ON SUNDAYS {SECTION 21(4)} AND PUBLIC HOLIDAYS {SECTION 22(4)}</h2>
    <h3> *NB! APPLICATION TO BE SUBMITTED PRIOR TO THE COMMENCEMENT OF OVERTIME</h3>
    <div class="section-title">1.	PARTICULARS OF APPLICANT:</div>
    <table>
        <tr>
            <td><strong>Name of employer/company</strong></td>
            <td>{{ $application->employer_name }}</td>
        </tr>
        <tr>
            <td><strong>Contact person (Mr., Ms., Mrs., Dr., Prof): </strong></td>
            <td>{{ $application->contact_person}}</td>
        </tr>
        <tr>
            <td><strong>Postal Address: </strong></td>
            <td>{{ $application->postal_address }}</td>
        </tr>
        <tr>
            <td><strong>Tel No: </strong></td>
            <td>{{ $application->tel_no }}</td>
        </tr>
        <tr>
            <td><strong>Email address: </strong></td>
            <td>{{ $application->email }}</td>
        </tr>
        
    </table>

    <div class="section-title">2.	DETAILS OF APPLICATION</div>
    <table>
        <tr>
            <td><strong>a.	Motivation and reasons why the application to increase the limits on overtime work should be granted: </strong></td>
            <td>{{ $application->motivation }}</td>
        </tr>
        <tr>
            <td><strong>b.	Proposed new overtime daily limit</strong></td>
            <td>{{ $application->proposed_daily_limit}}</td>
        </tr>
        <tr>
            <td><strong>c.	Proposed new overtime weekly limit</strong></td>
            <td>{{ $application->proposed_weekly_limit }}</td>
        </tr>
          <tr>
            <td><strong>d.	Work to be done on Sundays and Public Holidays</strong></td>
            <td>{{ $application->work_on_sundays }}</td>
        </tr>
                 <tr>
            <td><strong>e.	The class of employees to whom the notice applies: </strong></td>
            <td>{{ $application->class_of_employees }}</td>
        </tr>
                  <tr>
            <td><strong>f.	Provide consent/agreements of the affected employees (IT to provide link to upload consent)</strong></td>
            <td>{{ $application->employee_consent_link }}</td>
        </tr>
                  <tr>
            <td><strong>g.	Period for which overtime or Sundays or public holidays work is sought: </strong></td>
            <td>{{ $application->period_sought }}</td>
        </tr>
         <tr>
            <td><strong>Signature and date </strong></td>
            <td>{{ $application->signature_date }}</td>
        </tr>
    </table>
    <br><br>
    <p style="text-align:center;">Generated by MoJLR Exemption , Variation and Overtime Application System | {{ date('Y-m-d H:i') }}</p>

</body>
</html>
