<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Continuous Operation Application</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        h2 { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        td { padding: 6px; vertical-align: top; }
        td.label { width: 30%; font-weight: bold; }
        td.value { width: 70%; }
        .section-title { background: #f0f0f0; padding: 8px; font-weight: bold; margin-top: 20px; }
    </style>
</head>
<body>

    <h2>Exemption Application</h2>

    <div class="section-title">Employer Details</div>
        <table>
        <tr>
            <td class="label">Applicant Name:</td>
            <td class="value">{{ $application->applicant_name }}</td>
        </tr>
        <tr>
            <td class="label">Physical Address:</td>
            <td class="value">{{ $application->physical_address }}</td>
        </tr>
        <tr>
            <td class="label">Postal Address:</td>
            <td class="value">{{ $application->postal_address }}</td>
        </tr>
        <tr>
            <td class="label">Phone:</td>
            <td class="value">{{ $application->phone }}</td>
        </tr>
        <tr>
            <td class="label">Fax:</td>
            <td class="value">{{ $application->fax }}</td>
        </tr>
        <tr>
            <td class="label">Email:</td>
            <td class="value">{{ $application->email }}</td>
        </tr>
        <tr>
            <td class="label">Sector:</td>
            <td class="value">{{ $application->sector }}</td>
        </tr>
        <tr>
            <td class="label">Number of Employees:</td>
            <td class="value">{{ $application->num_employees }}</td>
        </tr>
    </table>

    <div class="section-title">Report Information</div>
    <table>
        <tr>
            <td class="label">Submitted First Report:</td>
            <td class="value">{{ $application->submitted_first_report }}</td>
        </tr>
        <tr>
            <td class="label">Report Reason:</td>
            <td class="value">{{ $application->report_reason }}</td>
        </tr>
        <tr>
            <td class="label">Report Date:</td>
            <td class="value">{{ $application->report_date }}</td>
        </tr>
    </table>

    <div class="section-title">Supporting Details</div>
    <table>
        <tr>
            <td class="label">Supporting Statement:</td>
            <td class="value">{{ $application->supporting_statement }}</td>
        </tr>
        <tr>
            <td class="label">Actions Taken:</td>
            <td class="value">{{ $application->actions_taken }}</td>
        </tr>
        <tr>
            <td class="label">Representative Name:</td>
            <td class="value">{{ $application->representative_name }}</td>
        </tr>
        <tr>
            <td class="label">Position:</td>
            <td class="value">{{ $application->position }}</td>
        </tr>
        <tr>
            <td class="label">Date Submitted:</td>
            <td class="value">{{ $application->date_submitted }}</td>
        </tr>
    </table>

    @if ($application->shift_roster)
        <p><strong>Shift Roster File:</strong> Attached (uploaded by user)</p>
    @endif

    @if ($application->approved_document)
        <p><strong>Approved Document:</strong> Attached (uploaded by admin)</p>
    @endif
    <br><br>
   <p style="text-align:center;">Generated by MoJLR Exemption , Variation and Overtime Application System | {{ date('Y-m-d H:i') }}</p>


</body>
</html>
